import { WalletDisconnectButton, WalletMultiButton } from '@solana/wallet-adapter-react-ui';
import Header from 'components/Header';
import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
    return (
        <div className="mt-4 mb-4">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className={styles.title}>
                Welcome to <a href="https://github.com/Sparker73/dapp-solana-playground">dapp-solana-playground</a>
            </h1>

            <div className={styles.walletButtons}>
                <WalletMultiButton />
                <WalletDisconnectButton />
            </div>

        </div>
    );
};

export default Home;
